#!/usr/bin/env python3
"""Point every absolute URL in the site at the canonical origin.

Most pages are generated and pick BASE up from siteconf. The issue pages under
DevOps/, Infrastructure/ and SRE/ are hand-written and are NOT regenerated by
the build, so they kept whichever origin was current the day they were written.

That is exactly the failure a canonical tag cannot survive: the page looks
fine, and the only symptom is a search engine indexing the wrong host. So
rather than editing those files once and hoping the next change remembers
them, this stage rewrites every known origin to BASE across every published
page, every build. Changing where the site lives stays a one-line edit in
siteconf.py.

Idempotent: a page already on BASE is left untouched.
"""
import os
import pathlib
import sys

ROOT = pathlib.Path(os.environ.get("PO_ROOT") or pathlib.Path(__file__).resolve().parent.parent)
sys.path.insert(0, str(ROOT / "tools"))

from siteconf import BASE, PAGES_ORIGIN     # noqa: E402

# Every origin this site has ever been served from. A page carrying any of
# these gets moved to BASE.
KNOWN = [
    PAGES_ORIGIN,
    "https://platform-ops-blog.vishal-abhinav.workers.dev/",
]

SKIP_NAMES = {"kit-template.html"}
touched = []

for f in sorted(ROOT.rglob("*.html")):
    if "tools" in f.parts or f.name in SKIP_NAMES:
        continue
    s = f.read_text(encoding="utf-8")
    out = s
    for origin in KNOWN:
        if origin != BASE:
            out = out.replace(origin, BASE)
    if out != s:
        f.write_text(out, encoding="utf-8")
        touched.append(f.relative_to(ROOT).as_posix())

# A stale origin left anywhere is a silent SEO bug, so fail loudly rather than
# reporting success over it.
stale = []
for f in sorted(ROOT.rglob("*.html")):
    if "tools" in f.parts or f.name in SKIP_NAMES:
        continue
    text = f.read_text(encoding="utf-8")
    for origin in KNOWN:
        if origin != BASE and origin in text:
            stale.append(f.relative_to(ROOT).as_posix())

assert not stale, f"origins still pointing away from BASE: {stale[:5]}"

# robots.txt names the sitemap by absolute URL. Left on the old origin it
# would send every crawler that found the canonical host to the OTHER host's
# sitemap — the exact split this change exists to close.
(ROOT / "robots.txt").write_text(
    "User-agent: *\n"
    "Allow: /\n"
    "\n"
    f"Sitemap: {BASE}sitemap.xml\n",
    encoding="utf-8")

# The licence and notice name the work by its public URL.
for name in ("LICENSE", "NOTICE"):
    f = ROOT / name
    if not f.exists():
        continue
    t = f.read_text(encoding="utf-8")
    out = t
    for origin in KNOWN:
        if origin != BASE:
            out = out.replace(origin, BASE)
    if out != t:
        f.write_text(out, encoding="utf-8")
        touched.append(name)

# The Kit email template is not a published page — it is pasted into Kit — but
# its links go out in actual emails, so it follows the canonical origin too.
kit = ROOT / "newsletter" / "kit-template.html"
if kit.exists():
    t = kit.read_text(encoding="utf-8")
    out = t
    for origin in KNOWN:
        if origin != BASE:
            out = out.replace(origin, BASE)
    if out != t:
        kit.write_text(out, encoding="utf-8")
        touched.append("newsletter/kit-template.html (re-paste this into Kit)")

print(f"canonical origin -> {BASE}")
print(f"  {len(touched)} page(s) rewritten"
      + (f", first: {touched[0]}" if touched else " (already canonical)"))
