import os, pathlib as _pl
ROOT = _pl.Path(os.environ.get("PO_ROOT") or _pl.Path(__file__).resolve().parent.parent)
TOOLS = ROOT / "tools"

# Per-category hub specs: slug, one-line tagline, and the architecture the
# category's topics actually form. Node names are taxonomy topic names, so
# status (live / pipeline / planned) and the link on a live node are resolved
# from taxonomy.py — a diagram can never claim something is live when it isn't.

SPEC = {
"Foundation": ("foundation",
 "The layer everything else sits on — the machine, the kernel, the shell, and the code you drive them with.",
 [("Machine", ["Computer Fundamentals", "Operating Systems"]),
  ("Operating systems", ["Linux", "Unix", "Windows Server"]),
  ("Interface", ["Shell & Bash", "Python"]),
  ("Craft", ["Programming Fundamentals", "Data Structures & Algorithms", "Git & Version Control"])]),

"IT Infrastructure": ("it-infrastructure",
 "Racks, servers and the design decisions that decide whether a data centre survives losing one of them.",
 [("Facility", ["Data Center", "Rack / Power / Cooling", "Hardware"]),
  ("Servers", ["Server Administration", "IT Infrastructure"]),
  ("Resilience", ["High Availability", "Fault Tolerance", "Disaster Recovery", "Business Continuity"]),
  ("Design", ["Capacity Planning", "Infrastructure Architecture", "Enterprise Infrastructure"])]),

"Storage": ("storage",
 "From a disk in a chassis to a replicated object store — and how to tell which layer is slow.",
 [("Media", ["Local Storage", "RAID", "LVM"]),
  ("Presentation", ["Block Storage", "File Storage", "Object Storage"]),
  ("Fabric", ["SAN", "NAS", "NFS", "SMB / CIFS"]),
  ("Operations", ["Storage Replication", "Storage Backup", "Storage Performance", "Storage Troubleshooting"])]),

"Virtualization": ("virtualization",
 "One physical host, many machines — hypervisors, their virtual hardware, and the lifecycle around them.",
 [("Hypervisor", ["Virtualization Fundamentals", "KVM", "QEMU", "Hyper-V"]),
  ("VMware stack", ["VMware", "ESXi", "vCenter"]),
  ("Virtual hardware", ["Virtual Networking", "Virtual Storage"]),
  ("Lifecycle", ["VM Lifecycle", "VM HA / DR"])]),

"Networking": ("networking",
 "Bottom to top: a frame on a wire becomes a routed packet becomes a load-balanced request.",
 [("Link", ["VLAN", "Switching", "ARP"]),
  ("Network", ["IPv4", "IPv6", "Subnetting", "Routing", "ICMP", "NAT"]),
  ("Routing protocols", ["BGP", "OSPF", "EIGRP", "MPLS"]),
  ("Transport", ["TCP", "UDP", "TCP/IP", "OSI Model"]),
  ("Services", ["DNS", "DHCP", "Proxy", "Load Balancing"]),
  ("Perimeter", ["VPN", "IPSec", "Firewall", "WAF", "Network Security"]),
  ("Modern", ["SDN", "SD-WAN", "Network Automation", "Network Monitoring"])]),

"Cloud": ("cloud",
 "The same primitives you rack yourself, rented by the hour — and what changes when someone else owns the hardware.",
 [("Providers", ["AWS", "Microsoft Azure", "Google Cloud"]),
  ("Primitives", ["Cloud Compute", "Cloud Storage", "Cloud Networking", "Cloud Databases"]),
  ("Control", ["Cloud IAM", "Cloud Security", "Cloud Monitoring"]),
  ("Continuity", ["Cloud Backup", "Cloud DR"]),
  ("Shape", ["Hybrid Cloud", "Multi-Cloud", "Cloud Migration", "Cloud Architecture"])]),

"DevOps": ("devops",
 "Commit to production: what runs between a push and a running workload, and how it rolls back.",
 [("Source", ["DevOps Fundamentals", "Continuous Integration"]),
  ("Build", ["Jenkins", "GitLab CI/CD", "GitHub Actions", "Azure DevOps", "Build Automation"]),
  ("Package", ["Artifact Management", "Pipeline Security"]),
  ("Release", ["Continuous Delivery", "Continuous Deployment", "Release Automation", "CI/CD"]),
  ("Rollout", ["Deployment Strategies", "Blue/Green Deployment", "Canary Deployment",
               "Rolling Deployment", "Feature Flags"]),
  ("Safety net", ["Rollback", "Pipeline Optimization", "DevOps Culture"])]),

"Containers": ("containers",
 "An image, a runtime and a namespace — the unit Kubernetes schedules.",
 [("Image", ["Container Images", "Container Registries"]),
  ("Runtime", ["Docker", "Podman", "Containerd", "CRI", "OCI", "Containers"]),
  ("Resources", ["Container Networking", "Container Storage"]),
  ("Operate", ["Container Security", "Container Troubleshooting"])]),

"Infrastructure as Code": ("infrastructure-as-code",
 "Infrastructure as reviewable text — plan, apply, and the state file that remembers what you own.",
 [("Author", ["Infrastructure as Code", "Terraform", "OpenTofu", "Pulumi"]),
  ("Compose", ["Terraform Modules", "Terraform Providers"]),
  ("State", ["Terraform State", "Remote State", "IaC Drift Management"]),
  ("Gate", ["IaC Testing", "IaC Security"])]),

"Configuration Management": ("configuration-management",
 "Declaring what a host should look like, then making every host look like it.",
 [("Engines", ["Configuration Management", "Ansible", "Puppet", "Chef", "Salt"]),
  ("Structure", ["Ansible Playbooks", "Roles", "Templates"]),
  ("Inputs", ["Inventories", "Variables", "Ansible Vault"]),
  ("At scale", ["AWX / Automation Platform"])]),

"GitOps": ("gitops",
 "Git as the only way in: the cluster reconciles itself towards whatever the repo says.",
 [("Source of truth", ["GitOps", "Git-based Infrastructure", "Declarative Deployment"]),
  ("Reconcilers", ["Argo CD", "Flux"]),
  ("Guardrails", ["Drift Detection", "GitOps Security"]),
  ("Delivery", ["Progressive Delivery"])]),

"Platform Engineering": ("platform-engineering",
 "Building the paved road so application teams stop rebuilding it themselves.",
 [("Product", ["Platform Engineering", "Platform-as-a-Product", "Developer Experience"]),
  ("Surface", ["Internal Developer Platform", "Backstage", "Developer Portals", "Platform APIs"]),
  ("Paths", ["Golden Paths", "Self-Service Infrastructure", "Platform Automation"]),
  ("Control", ["Platform Governance", "Platform Security"])]),

"Kubernetes": ("kubernetes",
 "The cluster from the API server down to a Pod's volume — and what to check when it breaks.",
 [("Control plane", ["Kubernetes Architecture", "Kubernetes Fundamentals",
                     "Scheduling", "Kubernetes Upgrade"]),
  ("Workloads", ["Pods", "Deployments", "ReplicaSets", "StatefulSets", "DaemonSets", "Jobs / CronJobs"]),
  ("Placement", ["Resource Requests/Limits", "Taints / Tolerations",
                 "Affinity / Anti-Affinity", "Probes"]),
  ("Networking", ["Kubernetes Networking", "Services", "Ingress", "CNI"]),
  ("Storage", ["Volumes", "Persistent Volumes", "Storage Classes", "CSI"]),
  ("Config & access", ["ConfigMaps", "Secrets", "RBAC", "Namespaces", "Kubernetes Security"]),
  ("Scale", ["Autoscaling", "HPA", "VPA", "Cluster Autoscaling"]),
  ("Day 2", ["Kubernetes Troubleshooting", "Kubernetes Backup",
             "Kubernetes Disaster Recovery", "Multi-Cluster Kubernetes"])]),

"OpenShift": ("openshift",
 "Kubernetes with the opinions pre-installed — Routes, SCCs, Operators, and the errors they cause.",
 [("Platform", ["OpenShift Fundamentals", "OpenShift Architecture", "Operators"]),
  ("Tenancy", ["Projects", "SCC", "OpenShift Security"]),
  ("Traffic & data", ["Routes", "OpenShift Networking", "OpenShift Storage"]),
  ("Day 2", ["OpenShift Monitoring", "OpenShift Logging",
             "OpenShift Troubleshooting", "OpenShift Upgrades"])]),

"Service Mesh": ("service-mesh",
 "A sidecar in every Pod, so traffic policy stops being every application's problem.",
 [("Data plane", ["Envoy", "Service Mesh"]),
  ("Control plane", ["Istio", "Linkerd"]),
  ("Traffic", ["Traffic Management", "Service Discovery"]),
  ("Security", ["mTLS", "Service-to-Service Security"]),
  ("Scale", ["Observability in Service Mesh", "Multi-Cluster Service Mesh"])]),

"SRE": ("sre",
 "Deciding how reliable is reliable enough, then running the loop that keeps it there.",
 [("Define", ["SRE Fundamentals", "SLI", "SLO", "SLA", "Error Budget"]),
  ("Measure", ["Availability", "Reliability", "Latency", "Scalability", "Service Health"]),
  ("Respond", ["Incident Management", "MTTR", "MTBF", "Problem Management"]),
  ("Learn", ["RCA", "Postmortem", "Reliability Engineering"]),
  ("Harden", ["Chaos Engineering", "Resilience Engineering",
              "Reliability Testing", "Capacity Planning"]),
  ("Sustain", ["Toil Reduction", "SRE Automation",
               "Production Readiness", "Operational Readiness"])]),

"Observability": ("observability",
 "Four signals out of a running system, and the alert that only fires when it matters.",
 [("Signals", ["Metrics", "Logs", "Traces", "Profiles"]),
  ("Collection", ["OpenTelemetry", "Telemetry Pipelines", "Observability"]),
  ("Metrics stack", ["Prometheus", "Grafana", "Monitoring"]),
  ("Logs stack", ["Loki", "ELK", "OpenSearch"]),
  ("Traces stack", ["Jaeger", "Tempo", "Distributed Tracing"]),
  ("From outside", ["Synthetic Monitoring", "Real User Monitoring",
                    "Application Performance Monitoring"]),
  ("Act", ["Alertmanager", "Alert Engineering", "Observability Architecture"])]),

"Logging": ("logging",
 "A line written on one host, searchable across a fleet — and dropped before it fills the disk.",
 [("Emit", ["Linux Logging", "Syslog", "Journald"]),
  ("Ship", ["Fluent Bit", "Fluentd", "Logstash", "Centralized Logging"]),
  ("Store", ["Elasticsearch", "OpenSearch", "Log Retention", "Log Rotation"]),
  ("Read", ["Kibana", "Log Correlation", "Log Security"])]),

"Performance Engineering": ("performance-engineering",
 "Find the resource that's saturated before you tune anything else.",
 [("Resources", ["CPU Performance", "Memory Performance", "Disk I/O", "Network Performance"]),
  ("Above the OS", ["Application Performance", "Database Performance"]),
  ("Prove it", ["Load Testing", "Stress Testing", "Benchmarking", "Profiling"]),
  ("Plan", ["Capacity Modeling", "Performance Troubleshooting"])]),

"Troubleshooting": ("troubleshooting",
 "The layer-by-layer sweep that turns 'it's broken' into a named cause.",
 [("Host", ["Linux Troubleshooting", "Performance Troubleshooting"]),
  ("Plumbing", ["Network Troubleshooting", "Storage Troubleshooting", "Database Troubleshooting"]),
  ("Platform", ["Kubernetes Troubleshooting", "Cloud Troubleshooting"]),
  ("Application", ["Application Troubleshooting", "Security Troubleshooting"]),
  ("Close it out", ["Production Incident Troubleshooting", "Root Cause Analysis", "Failure Analysis"])]),

"Backup & DR": ("backup-dr",
 "Backups nobody has restored are not backups. The targets, the copies, and the drill.",
 [("Targets", ["RPO", "RTO"]),
  ("Copies", ["Full Backup", "Incremental Backup", "Differential Backup",
              "Snapshot", "Replication", "Backup Fundamentals"]),
  ("Topology", ["DR Architecture", "Active/Active", "Active/Passive"]),
  ("Prove it", ["Backup Validation", "Restore Testing", "DR Drill"]),
  ("Switch", ["Failover", "Failback"])]),

"ITSM & Operations": ("itsm-operations",
 "The paperwork that makes operations repeatable instead of heroic.",
 [("Framework", ["ITIL", "Operational Documentation"]),
  ("Reactive", ["Incident Management", "Problem Management", "Event Management", "Service Request"]),
  ("Planned", ["Change Management", "Release Management", "CAB", "Change Windows"]),
  ("Records", ["CMDB", "Asset Management", "Configuration Management"]),
  ("Tools", ["ServiceNow", "Remedy"])]),

"Security": ("security",
 "Identity at the front, secrets in the middle, and evidence for the auditor at the end.",
 [("Foundations", ["Cybersecurity Fundamentals", "Zero Trust", "Compliance"]),
  ("Identity", ["IAM", "RBAC", "PAM", "LDAP", "Active Directory"]),
  ("Federation", ["SSO", "OAuth", "OIDC", "SAML"]),
  ("Crypto", ["PKI", "TLS/SSL", "Certificates"]),
  ("Secrets", ["Secrets Management", "HashiCorp Vault"]),
  ("Layers", ["Infrastructure Security", "Network Security", "Linux Security", "Cloud Security",
              "Container Security", "Kubernetes Security", "Application Security"]),
  ("Detect", ["SIEM", "SOC", "Threat Detection", "Vulnerability Management",
              "Security Scanning", "Security Auditing", "DevSecOps"])]),

"Supply Chain Security": ("supply-chain-security",
 "Proving the artifact you're about to run is the one you built.",
 [("Build", ["Software Supply Chain Security", "SLSA", "CI/CD Security", "Dependency Security"]),
  ("Describe", ["SBOM", "Container Image Scanning", "Secrets Scanning"]),
  ("Sign", ["Artifact Signing", "Image Signing", "Cosign"]),
  ("Admit", ["Admission Control", "Policy as Code", "OPA", "Gatekeeper", "Kyverno"])]),

"Database": ("database",
 "Where the state lives — and what happens to it when the primary dies.",
 [("Relational", ["PostgreSQL", "MySQL", "Oracle", "SQL Server", "Database Fundamentals"]),
  ("Non-relational", ["MongoDB", "Redis"]),
  ("Availability", ["Database Replication", "Database HA", "Connection Management"]),
  ("Recovery", ["Database Backup", "Database Recovery"]),
  ("Run it", ["Query Optimization", "Database Performance",
              "Database Monitoring", "Database Security"])]),

"Middleware": ("middleware",
 "The tier between the browser and the database — web servers, app servers and queues.",
 [("Web tier", ["Nginx", "Apache"]),
  ("App servers", ["Tomcat", "WildFly", "JBoss", "Application Servers"]),
  ("Messaging", ["RabbitMQ", "Apache Kafka", "Redis", "Message Queues"]),
  ("Patterns", ["Event Streaming", "Event-Driven Architecture"]),
  ("Operate", ["Middleware HA", "Middleware Troubleshooting"])]),

"API & Microservices": ("api-microservices",
 "Small services over HTTP, and the patterns that stop one slow call taking the system down.",
 [("Protocol", ["HTTP/HTTPS", "REST APIs"]),
  ("Edge", ["API Gateway", "API Management", "Rate Limiting"]),
  ("Access", ["Authentication", "Authorization", "API Security"]),
  ("Services", ["Microservices", "Service Discovery", "Event-Driven Microservices"]),
  ("Resilience", ["Circuit Breaker", "Retry", "Timeout", "Bulkhead"]),
  ("Consistency", ["Distributed Transactions"])]),

"Distributed Systems": ("distributed-systems",
 "What you give up to run across more than one machine, and the algorithms that manage the loss.",
 [("Limits", ["CAP Theorem", "Partition Tolerance", "Failure Domains", "Distributed Systems"]),
  ("Agreement", ["Consensus", "Quorum", "Leader Election", "Distributed Coordination"]),
  ("Copies", ["Replication", "Consistency", "Eventual Consistency"]),
  ("Coordination", ["Distributed Locking", "Distributed Transactions", "Caching"])]),

"AI Infrastructure": ("ai-infrastructure",
 "GPUs, model servers, and the operational surface a model picks up once it's serving traffic.",
 [("Silicon", ["GPU Infrastructure", "GPU Scheduling", "GPU Kubernetes", "AI Infrastructure"]),
  ("Workloads", ["AI Workloads on Kubernetes", "AI CI/CD", "MLOps", "LLMOps"]),
  ("Serving", ["Model Serving", "Inference Infrastructure", "Model Gateways"]),
  ("Retrieval", ["RAG Infrastructure", "Vector Databases"]),
  ("Operate", ["Model Monitoring", "Model Observability", "AI Reliability",
               "AI Cost Management", "AI Infrastructure Automation"]),
  ("Control", ["AI Security", "AI Governance"])]),

"AIOps": ("aiops",
 "Pointing models at your own telemetry — and deciding how much they're allowed to touch.",
 [("Ingest", ["AI Log Analysis", "AI Alert Correlation", "AIOps"]),
  ("Diagnose", ["AI Incident Detection", "AI Root Cause Analysis", "AI-assisted Troubleshooting"]),
  ("Predict", ["AI Capacity Forecasting"]),
  ("Act", ["AI Remediation", "AI Operations Agents", "Agentic DevOps",
           "Agentic SRE", "Agentic CloudOps"]),
  ("Restraint", ["Human-in-the-loop Automation", "AI Operational Guardrails"])]),

"FinOps": ("finops",
 "Knowing what each workload costs before finance asks.",
 [("See it", ["Cloud Cost Management", "Cost Allocation", "Tagging", "FinOps"]),
  ("Shrink it", ["Rightsizing", "Resource Optimization", "Cloud Waste Management"]),
  ("Buy better", ["Reserved Capacity", "Spot / Preemptible Instances"]),
  ("Keep it down", ["Kubernetes Cost Management", "Cost Governance"])]),

"Automation": ("automation",
 "Everything you'd rather not do twice — from a shell loop to a cluster that repairs itself.",
 [("Scripting", ["Shell Automation", "Bash Automation", "Python Automation"]),
  ("Config & infra", ["Ansible Automation", "Terraform Automation", "Cloud Automation"]),
  ("Interfaces", ["API Automation", "Network Automation", "Database Automation"]),
  ("Closing the loop", ["Kubernetes Automation", "Monitoring Automation",
                        "Self-Healing Infrastructure"])]),

"Architecture": ("architecture",
 "The shapes systems take once they have to survive a region, a tenant, or a deploy.",
 [("Base", ["System Architecture", "Distributed Architecture"]),
  ("Decomposition", ["Microservice Architecture", "Event-Driven Architecture"]),
  ("Qualities", ["Scalable Architecture", "Resilient Architecture", "Zero-Downtime Architecture"]),
  ("Footprint", ["Multi-Region Architecture", "Multi-Cloud Architecture",
                 "Hybrid Architecture", "Multi-Tenant Architecture"])]),
}
