"""Kubernetes + OpenShift — the complete topic list.

Source: the reader-submitted requirement list (46 numbered groups, concepts
plus the error/state vocabulary for each). Transcribed verbatim and in the
same order and grouping as given — this file does not re-organize it,
because the grouping itself is what the reader asked to see reproduced.

GROUPS = [ (group_title, [item, item, ...]), ... ]   — 46 entries, in order.

Status (live / pipeline / planned) is NOT decided here. build_topicmap.py
decides it by checking whether each item's text actually appears on a
published page — this file only holds what the reader asked to see, not an
opinion about how much of it is done.
"""

GROUPS = [
("Kubernetes Fundamentals", [
 "Kubernetes architecture","Kubernetes components","Control Plane","Worker Nodes","API Server",
 "etcd","Scheduler","Controller Manager","Kubelet","kube-proxy","Container Runtime",
 "Kubernetes API","Objects and Resources","Namespaces","Labels","Selectors","Annotations",
 "YAML manifests","Declarative vs imperative management","kubectl","Contexts","Kubeconfig",
 "Resource quotas","Limit ranges","Kubernetes events","Finalizers","OwnerReferences",
 "Garbage collection",
]),
("Pods", [
 "Pod architecture","Single-container Pod","Multi-container Pod","Init containers",
 "Sidecar containers","Ephemeral containers","Pod lifecycle","Pod phases","Pod conditions",
 "Pod restart policy","Pod termination","Graceful shutdown","Pod disruption","Pod affinity",
 "Pod anti-affinity","Topology spread constraints","Static Pods","HostNetwork","HostPID",
 "HostPath","SecurityContext",
 "Pending","ContainerCreating","Running","Succeeded","Failed","Unknown","CrashLoopBackOff",
 "ImagePullBackOff","ErrImagePull","CreateContainerConfigError","CreateContainerError",
 "RunContainerError","OOMKilled","Evicted","Terminating","Completed","Init:Error",
 "Init:CrashLoopBackOff","Init:ImagePullBackOff","PodSandboxChanged","FailedCreatePodSandBox",
 "FailedKillPod","DeadlineExceeded",
]),
("Deployments", [
 "Deployment","ReplicaSet","ReplicationController","Rolling update","Recreate strategy",
 "Rollback","Revision history","Scaling","Horizontal scaling","Deployment strategy",
 "Deployment availability","maxSurge","maxUnavailable","Deployment conditions",
 "ProgressDeadlineExceeded","ReplicaFailure","MinimumReplicasUnavailable","Deployment stuck",
 "Deployment rollout stuck","ReplicaSet not creating Pods","Old ReplicaSet not terminating",
 "New ReplicaSet unavailable","Failed rollout","Failed rollback",
]),
("Stateful Applications", [
 "StatefulSet","Headless Service","Stable network identity","Persistent identity",
 "Ordered deployment","Ordered termination","Persistent storage","StatefulSet scaling",
 "StatefulSet update strategy",
 "PVC stuck","Pod stuck terminating","Pod cannot attach volume","Pod cannot mount volume",
 "Ordered deployment failure","Volume attachment failure","Persistent identity problems",
]),
("DaemonSets", [
 "DaemonSet architecture","Node selectors","Taints and tolerations","Rolling updates",
 "DaemonSet scheduling",
 "Desired vs current mismatch","DaemonSet Pod not scheduled","Taint-related scheduling failure",
 "Node selector mismatch","Image pull failure","HostPort conflict",
]),
("Jobs & CronJobs", [
 "Job","CronJob","Scheduled workloads","Parallel jobs","Completion count","Backoff limit",
 "Concurrency policy","Job history","Successful jobs","Failed jobs",
 "Job failed","BackoffLimitExceeded","DeadlineExceeded","CronJob not triggering",
 "CronJob suspended","Duplicate jobs","Job Pod stuck","Job Pod OOMKilled",
]),
("Services", [
 "ClusterIP","NodePort","LoadBalancer","ExternalName","Headless Service","Service selectors",
 "Endpoints","EndpointSlices","Service discovery","DNS","Internal communication",
 "Service has no endpoints","Wrong selector","Connection refused","Connection timeout",
 "DNS resolution failure","NXDOMAIN","SERVFAIL","Port mismatch","TargetPort mismatch",
 "Endpoint unavailable",
]),
("Networking", [
 "Kubernetes networking model","CNI","Pod-to-Pod networking","Pod-to-Service","Pod-to-external",
 "External-to-Pod","Network namespaces","Virtual Ethernet","Routing","IP tables","IPVS",
 "NetworkPolicy","Ingress","Gateway API","DNS","CoreDNS",
 "Connection refused","Connection timed out","No route to host","Network unreachable",
 "DNS failure","Service unreachable","Pod unreachable","CNI failure","CNI timeout",
 "IP allocation failure","IP exhaustion","NetworkPolicy blocking traffic","MTU mismatch",
 "Broken overlay network","Endpoint missing",
]),
("Ingress", [
 "Ingress","Ingress Controller","IngressClass","TLS","Certificates","Host-based routing",
 "Path-based routing","Rewrite","Backend services",
 "404","400","401","403","502","503","504","TLS handshake failure","Certificate expired",
 "Certificate mismatch","Backend unavailable","DNS not resolving",
]),
("Storage", [
 "PersistentVolume","PersistentVolumeClaim","StorageClass","Dynamic provisioning",
 "Static provisioning","CSI","Volume snapshots","Volume cloning","Access modes",
 "Reclaim policy","Storage capacity","Volume expansion",
 "PVC Pending","PV Pending","Mount failure","Attach failure","Detach failure",
 "Multi-Attach error","FailedMount","FailedAttachVolume","FailedMountVolume",
 "Permission denied","Read-only filesystem","Disk full","Storage exhausted",
 "CSI driver failure","Volume provisioning failure",
]),
("ConfigMap & Secrets", [
 "ConfigMap","Secret","Environment variables","Volume-mounted configuration","Secret rotation",
 "Encryption at rest","External secrets",
 "ConfigMap not found","Secret not found","Invalid environment variable","Incorrect secret",
 "Permission denied","Secret mount failure","Configuration mismatch",
]),
("Scheduling", [
 "Scheduler","Requests","Limits","NodeSelector","NodeAffinity","PodAffinity","PodAntiAffinity",
 "Taints","Tolerations","PriorityClass","Preemption","Topology constraints",
 "0/X nodes are available","Insufficient CPU","Insufficient memory",
 "Insufficient ephemeral storage","Untolerated taint","Node selector mismatch",
 "Node affinity mismatch","Pod affinity failure","Pod anti-affinity failure",
 "HostPort conflict","PVC topology conflict","Preemption failure",
]),
("Resources", [
 "CPU requests","CPU limits","Memory requests","Memory limits","Ephemeral storage",
 "QoS classes","Guaranteed","Burstable","BestEffort","ResourceQuota","LimitRange",
 "OOMKilled","Evicted","CPU throttling","Memory pressure","Disk pressure","PID pressure",
 "Node pressure","Resource quota exceeded",
]),
("Security", [
 "RBAC","Role","ClusterRole","RoleBinding","ClusterRoleBinding","ServiceAccount",
 "Authentication","Authorization","Admission controllers","Pod Security","SecurityContext",
 "Linux capabilities","Seccomp","AppArmor","SELinux","NetworkPolicy","Secrets",
 "Forbidden","Unauthorized","401","403","ServiceAccount not found","RBAC denied","SCC denied",
 "SELinux denial","Permission denied","Privileged container denied",
]),
("Kubernetes Certificates", [
 "Cluster CA","API Server certificate","Kubelet certificate","etcd certificate",
 "Client certificates","Certificate rotation","CSR","Certificate expiry",
 "Certificate expired","x509: certificate has expired","certificate signed by unknown authority",
 "TLS handshake failure","Invalid certificate","Certificate mismatch",
 "Kubelet authentication failure",
]),
("etcd", [
 "etcd architecture","Leader election","Raft","Quorum","Snapshots","Restore","Backup",
 "Compaction","Defragmentation",
 "No leader","Lost quorum","Slow etcd","High DB size","Corrupt database","Disk full",
 "Member unavailable","Connection refused","Timeout","Failed snapshot","Failed restore",
]),
("Control Plane", [
 "API Server","Scheduler","Controller Manager","etcd","Controller loops","Admission",
 "API aggregation",
 "API Server unavailable","API Server timeout","Scheduler unavailable",
 "Controller Manager unavailable","etcd unavailable","API request timeout","API rate limiting",
 "Leader election failure","Control-plane certificate failure",
]),
("Kubelet", [
 "Kubelet architecture","Pod lifecycle","Container runtime integration","CNI integration",
 "CSI integration","Static Pods","Node registration","Health checks",
 "Kubelet not running","Node NotReady","Runtime unavailable","CNI unavailable",
 "Failed Pod sync","Failed mount","Failed container creation","Certificate failure",
 "Lease update failure","Heartbeat failure",
]),
("Container Runtime", [
 "containerd","CRI-O","CRI","Image management","Container lifecycle","Runtime configuration",
 "Runtime unavailable","Image pull failure","Container creation failure",
 "Container start failure","Container stop timeout","Runtime timeout",
 "Sandbox creation failure","CRI connection failure",
]),
("Container Images", [
 "Image registry","Image tags","Image digest","ImagePullPolicy","Private registry",
 "Image authentication","Image scanning","Image signing",
 "ErrImagePull","ImagePullBackOff","manifest unknown","unauthorized","denied",
 "repository does not exist","TLS certificate error","connection timeout",
 "DNS resolution failure","Image architecture mismatch",
]),
("Health Checks", [
 "Liveness Probe","Readiness Probe","Startup Probe","HTTP probe","TCP probe","Exec probe",
 "gRPC probe",
 "Liveness probe failed","Readiness probe failed","Startup probe failed","HTTP 500",
 "HTTP 404","Connection refused","Timeout","Probe command failure",
]),
("Autoscaling", [
 "HPA","VPA","Cluster Autoscaler","Metrics Server","Custom metrics","External metrics",
 "Metrics unavailable","HPA unable to calculate","Target CPU unavailable",
 "VPA recommendation failure","Cluster Autoscaler failure","Nodes not scaling",
 "Pods pending after scale",
]),
("Observability", [
 "Logging","Monitoring","Metrics","Events","Tracing","Prometheus","Grafana","Alertmanager",
 "OpenTelemetry",
 "Metrics unavailable","Target down","Scrape failure","Prometheus unavailable",
 "Alertmanager unavailable","High cardinality","Missing metrics","Log ingestion failure",
]),
("Kubernetes Troubleshooting", [
 "kubectl get pods","kubectl describe pod","kubectl logs","kubectl logs --previous",
 "kubectl exec","kubectl get events","kubectl get nodes","kubectl describe node",
 "kubectl get svc","kubectl get endpoints","kubectl get ingress","kubectl get pvc",
 "kubectl get pv","kubectl get deploy","kubectl get rs","kubectl get ds","kubectl get sts",
 "kubectl get jobs","kubectl get cronjobs","kubectl top pods","kubectl top nodes",
]),
("OpenShift Fundamentals", [
 "OpenShift architecture","OpenShift vs Kubernetes","OpenShift Container Platform",
 "OpenShift Kubernetes Engine","OpenShift Dedicated","Red Hat OpenShift Service on AWS",
 "Control Plane","Worker","Infrastructure nodes","Machine Config Pool","Operators",
 "Operator Lifecycle Manager","CRD","Custom Resources","Projects","Routes","ImageStreams",
 "BuildConfigs","DeploymentConfigs","Security Context Constraints","Cluster Operators",
 "Machine Config Operator",
]),
("OpenShift CLI", [
 "oc login","oc whoami","oc project","oc get","oc describe","oc logs","oc exec","oc rsh",
 "oc debug","oc adm","oc apply","oc create","oc delete","oc edit","oc patch","oc rollout",
 "oc scale","oc expose","oc port-forward","oc rsync",
]),
("OpenShift Projects", [
 "Projects","Project quotas","Project limits","Project annotations","Project administrators",
 "Namespace isolation",
 "Forbidden","Project does not exist","Unauthorized","ResourceQuota exceeded",
 "LimitRange violation","RBAC failure",
]),
("OpenShift Routes", [
 "Route","Edge termination","Passthrough","Re-encrypt","TLS","HAProxy router","Route sharding",
 "Wildcard routes",
 "503 Service Unavailable","503 Application is not available","404","TLS error",
 "Certificate error","Backend unavailable","Service selector mismatch","Route not admitted",
]),
("OpenShift Security Context Constraints — SCC", [
 "SCC architecture","restricted","restricted-v2","anyuid","privileged","nonroot","hostnetwork",
 "ServiceAccount assignment","UID ranges","SELinux context","Linux capabilities",
 "unable to validate against any security context constraint","Forbidden",
 "unable to validate against any SCC","RunAsUser violation","FSGroup violation",
 "SELinux violation","Privileged container denied","HostNetwork denied",
]),
("OpenShift Operators", [
 "Operator","OLM","OperatorHub","Subscription","CSV","InstallPlan","CatalogSource",
 "ClusterServiceVersion","CustomResourceDefinition","Custom Resource",
 "CSV Pending","CSV Failed","Subscription failure","InstallPlan failure",
 "CatalogSource unavailable","Operator degraded","Operator unavailable","CRD missing",
 "Webhook failure",
]),
("OpenShift Cluster Operators", [
 "authentication","baremetal","cloud-controller-manager","cloud-credential",
 "cluster-autoscaler","config","console","control-plane-machine-set","dns","etcd",
 "image-registry","ingress","insights","kube-apiserver","kube-controller-manager",
 "kube-scheduler","kube-storage-version-migrator","machine-api","machine-config",
 "marketplace","monitoring","network","node-tuning","openshift-apiserver",
 "openshift-controller-manager","operator-lifecycle-manager",
 "operator-lifecycle-manager-catalog","service-ca","storage",
 "Available=False","Progressing=True","Degraded=True","Upgradeable=False",
]),
("OpenShift Nodes", [
 "Node architecture","Machine","MachineSet","MachineHealthCheck","Node labels","Node taints",
 "Node conditions","Cordoning","Draining","Uncordoning",
 "NotReady","Ready=False","MemoryPressure","DiskPressure","PIDPressure","NetworkUnavailable",
 "Node unreachable","Kubelet down","Container runtime down","Node reboot","Kernel panic",
 "Disk full","Memory exhaustion","Certificate expiry",
]),
("MachineConfig", [
 "MachineConfig","MachineConfigPool","MachineConfig Operator","OS configuration",
 "Kernel arguments","SSH configuration","Systemd configuration","Filesystem configuration",
 "Node reboot",
 "MCP Updating","MCP Degraded","MCP Paused","MachineConfig rollout stuck",
 "Node unable to update","OS update failure","MachineConfig conflict","Reboot loop",
]),
("OpenShift Networking", [
 "OVN-Kubernetes","OpenShift SDN","CNI","Node networking","Cluster Network Operator",
 "NetworkPolicy","Egress","Ingress","DNS","Service network","Cluster network","Host network",
 "CNO degraded","OVN failure","OVN DB issue","DNS failure","Pod network unavailable",
 "Node network unavailable","Service unreachable","Route unreachable","Egress failure",
 "NetworkPolicy block","IP exhaustion",
]),
("OpenShift Image Registry", [
 "Internal registry","ImageStream","ImageStreamTag","ImageStreamImage","Registry storage",
 "Registry authentication","Image pruning",
 "Image pull failure","Push failure","Registry unavailable","Registry storage full",
 "Unauthorized","Blob unknown","Manifest unknown","ImageStream not updating",
]),
("OpenShift Builds", [
 "BuildConfig","Build","Source-to-Image","Docker builds","Build strategies","Build triggers",
 "Build hooks",
 "Build Failed","Build Error","Build stuck","Image push failure","Source download failure",
 "Registry failure","Builder Pod failure","Resource exhaustion",
]),
("OpenShift Monitoring", [
 "Prometheus","Alertmanager","Thanos","Grafana","kube-state-metrics","node-exporter",
 "User Workload Monitoring","Platform Monitoring","PrometheusRule","ServiceMonitor",
 "PodMonitor",
 "Prometheus CrashLoopBackOff","Prometheus OOM","Target down","Scrape failure",
 "Alertmanager failure","Thanos failure","Metrics missing","PVC full","Query timeout",
]),
("OpenShift Storage", [
 "CSI","StorageClass","PV","PVC","CSI drivers","Volume snapshots","Dynamic provisioning",
 "Storage operators",
 "PVC Pending","Mount failure","Attach failure","CSI timeout","Multi-Attach","Storage full",
 "Permission denied","Volume provisioning failure",
]),
("OpenShift Authentication", [
 "OAuth","OAuth Server","Identity Providers","LDAP","Active Directory","HTPasswd",
 "OpenID Connect","ServiceAccounts","Tokens",
 "Login failure","Token expired","OAuth unavailable","LDAP authentication failure",
 "Identity provider unavailable","Unauthorized","Forbidden",
]),
("OpenShift API", [
 "Kubernetes API","OpenShift API","API Server","OAuth API","API aggregation","API groups",
 "CRDs","Webhooks",
 "401 Unauthorized","403 Forbidden","404 Not Found","409 Conflict","429 Too Many Requests",
 "500 Internal Server Error","503 Service Unavailable","504 Gateway Timeout","API timeout",
 "Certificate failure",
]),
("OpenShift Web Console", [
 "Console","Developer perspective","Administrator perspective","Projects","Workloads",
 "Networking","Storage","Operators","Monitoring","Events","Logs","Topology",
 "Console unavailable","Login failure","API unavailable","Blank page","Route failure",
 "OAuth failure","Certificate error",
]),
("OpenShift Upgrade", [
 "Cluster upgrade","Channel","Update graph","ClusterVersion","ClusterVersionOperator",
 "Upgrade prechecks","Control-plane upgrade","Worker upgrade","Operator compatibility",
 "Upgrade blocked","Upgrade stuck","CVO degraded","Operator incompatible","MCP stuck",
 "Node unavailable","API unavailable","Certificate issues","Image pull failure",
 "Upgrade rollback/recovery",
]),
("Disaster Recovery", [
 "etcd backup","etcd restore","Application backup","Velero","OADP","PV backup",
 "Cluster recovery","Control-plane recovery","DR cluster","RTO","RPO",
 "Backup failure","Restore failure","Missing PVC","Missing secrets","Missing CRDs",
 "etcd restore failure","Application dependency failure","DNS failure","Route failure",
]),
("Performance Troubleshooting", [
 "CPU utilization","Memory utilization","Load average","Disk I/O","Network I/O",
 "Container throttling","JVM heap","Garbage collection","Connection pools","Thread pools",
 "API latency","Pod latency","Service latency",
 "High CPU","High memory","OOMKilled","CPU throttling","Disk full","Disk latency",
 "Network latency","Connection timeout","Connection refused","Thread exhaustion",
 "Connection pool exhaustion","JVM heap exhaustion","GC pause","Pod restart","Node pressure",
]),
("Application Troubleshooting", [
 "Application logs","Container logs","Previous container logs","Application ports",
 "Environment variables","ConfigMaps","Secrets","Dependencies","Database connectivity",
 "API connectivity","External service connectivity","Connection pools","Thread pools",
 "Connection refused","Connection timed out","Read timeout","Connect timeout","Broken pipe",
 "Connection reset","Socket timeout","DNS resolution failure","Authentication failure",
 "HTTP 400","HTTP 401","HTTP 403","HTTP 404","HTTP 409","HTTP 429","HTTP 500","HTTP 502",
 "HTTP 503","HTTP 504","OOMKilled","CrashLoopBackOff",
]),
("Database Connectivity from Kubernetes/OpenShift", [
 "Service DNS","DB hostname","DB port","NetworkPolicy","Firewall","TLS","Credentials",
 "Connection pool","DB max connections","Application timeout","DB timeout","Connection leak",
 "Connection refused","Connection timeout","Too many connections","Communications link failure",
 "Connection reset","Broken pipe","Read timed out","Authentication failed",
 "SSL handshake failure","Unknown host","Host unreachable","Pool exhausted","Connection leak",
]),
]

assert len(GROUPS) == 46, f"expected 46 groups, got {len(GROUPS)}"
